### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by Kaneki676** [Rapadapl/podkol-bot#2]
не запускается, может я что-то не то сделал или не так установил но выдаёт ошибку
var fetch = require('node-fetch');
            ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\vlad\Desktop\podkol-bot-main\node_modules\node-fetch\src\index.js from C:\Users\vlad\Desktop\podkol-bot-main\node_modules\easyvk\lib\bundle.js not supported.
Instead change the require of index.js in C:\Users\vlad\Desktop\podkol-bot-main\node_modules\easyvk\lib\bundle.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> ←[90m(C:\Users\vlad\Desktop\podkol-bot-main\←[39mnode_modules\←[4measyvk←[24m\lib\bundle.js:8:13←[90m)←[39m
    at Object.<anonymous> ←[90m(C:\Users\vlad\Desktop\podkol-bot-main\←[39mindex.js:5:16←[90m)←[39m {
  code: ←[32m'ERR_REQUIRE_ESM'←[39m
}

Node.js v18.12.1

**Comment by Rapadapl** [comment]
Там ВК обновил API, а я не обновлял код, потому что забросил проект (я ленивая жопа). Я обязательно когда нибудь его закончу
